import type { Planet } from "../types/global";

// Importing Planet Icons
import { FaEarthAmericas } from "react-icons/fa6"; // Earth
import { SiPlanetscale } from "react-icons/si"; // Mercury, Venus, Mars, Jupiter, Neptune
import { GiRingedPlanet } from "react-icons/gi"; // Saturn
import { RiPlanetFill } from "react-icons/ri"; // Uranus

export const PlanetData: Planet[] = [
  {
    name: "Mercury",
    iconScale: 25,
    icon: SiPlanetscale,
    avgTempF: 333,
    avgTempC: 167,
    meter: 20,
    color: "Gray",
    surfaceType: "Rocky",
    sizeKM: 4880,
    sizeMI: 3032,
    moons: 0,
    rings: false,
  },
  {
    name: "Venus",
    iconScale: 39,
    icon: SiPlanetscale,
    avgTempF: 867,
    avgTempC: 464,
    meter: 5,
    color: "Yellow",
    surfaceType: "Rocky",
    sizeKM: 12104,
    sizeMI: 7521,
    moons: 0,
    rings: false,
  },
  {
    name: "Earth",
    iconScale: 40,
    icon: FaEarthAmericas,
    avgTempF: 59,
    avgTempC: 15,
    meter: 50,
    color: "Blue/Green",
    surfaceType: "Rocky",
    sizeKM: 12742,
    sizeMI: 7918,
    moons: 1,
    rings: false,
  },
  {
    name: "Mars",
    iconScale: 30,
    icon: SiPlanetscale,
    avgTempF: -85,
    avgTempC: -65,
    meter: 60,
    color: "Red",
    surfaceType: "Rocky",
    sizeKM: 6779,
    sizeMI: 4212,
    moons: 2,
    rings: false,
  },
  {
    name: "Jupiter",
    iconScale: 90,
    icon: SiPlanetscale,
    avgTempF: -166,
    avgTempC: -110,
    meter: 72,
    color: "Brown/Orange",
    surfaceType: "Gas",
    sizeKM: 139820,
    sizeMI: 86881,
    moons: 95,
    rings: false,
  },
  {
    name: "Saturn",
    iconScale: 80,
    icon: GiRingedPlanet,
    avgTempF: -220,
    avgTempC: -140,
    meter: 80,
    color: "Yellow",
    surfaceType: "Gas",
    sizeKM: 116460,
    sizeMI: 72366,
    moons: 274,
    rings: true,
  },
  {
    name: "Uranus",
    iconScale: 70,
    icon: RiPlanetFill,
    avgTempF: -320,
    avgTempC: -195,
    meter: 87,
    color: "Blue-Green",
    surfaceType: "Ice/Gas",
    sizeKM: 50724,
    sizeMI: 31518,
    moons: 28,
    rings: true,
  },
  {
    name: "Neptune",
    iconScale: 70,
    icon: SiPlanetscale,
    avgTempF: -330,
    avgTempC: -200,
    meter: 93,
    color: "Blue",
    surfaceType: "Ice/Gas",
    sizeKM: 49244,
    sizeMI: 30598,
    moons: 16,
    rings: false,
  },
];

export const PlanetImages = {};
