/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

// Importing types
import { type GLTF } from "three-stdlib";
import { type Dispatch, type JSX, type SetStateAction } from "react";
import type { DialogueEntry, Planet, PlanetProgression } from "../types/global";
import { TutorialDialogue, TutorialManager } from "../constants/PlanetTutorial";

import useSound from "use-sound";
import ShipSelect from "/sounds/ShipSelect.wav";
import LeverCrank from "/sounds/LeverCrank.mp3";
import ButtonClick from "/sounds/ButtonClicked.mp3";

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube003_2: THREE.Mesh;
    Cube003_3: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
    Cylinder002_1: THREE.Mesh;
    Cylinder002_2: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube025_1: THREE.Mesh;
    Cube002: THREE.Mesh;
    Plane: THREE.Mesh;
    Screen001: THREE.Mesh;
    Screen002: THREE.Mesh;
    MeterScreen: THREE.Mesh;
    MeterScreen001: THREE.Mesh;
    BarScreen: THREE.Mesh;
    BarScreen001: THREE.Mesh;
    BarScreen002: THREE.Mesh;
    ShipLights: THREE.Mesh;
    ShipLights001: THREE.Mesh;
    ShipLights002: THREE.Mesh;
    ShipLights003: THREE.Mesh;
  };
  materials: {
    ["Ship Metal"]: THREE.MeshStandardMaterial;
    ["Ship Bearing"]: THREE.MeshStandardMaterial;
    ["Screen Border"]: THREE.MeshStandardMaterial;
    Void: THREE.MeshStandardMaterial;
    Button: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
  };
};

// Custom reusable components
const LightMaterial = () => {
  return (
    <meshStandardMaterial
      color={0x6fffe9}
      emissive={0x6fffe9}
      emissiveIntensity={4}
    />
  );
};

// Props for the Model
type ShipProps = {
  props?: JSX.IntrinsicElements["group"];
  setHoveredElement: Dispatch<SetStateAction<string | null>>;
  setCurrentTutorialText: Dispatch<SetStateAction<DialogueEntry[] | null>>;
  setTutorialIndex: Dispatch<SetStateAction<number>>;
  setTutorialStep: Dispatch<SetStateAction<number>>;
  setCurrentScreen: Dispatch<SetStateAction<string | null>>;
  setScreenSelected: Dispatch<SetStateAction<boolean>>;
  setPlanets: Dispatch<SetStateAction<Record<string, PlanetProgression>>>;
  setEnteredAtmos: Dispatch<SetStateAction<boolean>>;
  showDataCollected: () => void;
  talking: boolean;
  tutorial: boolean;
  tutorialStep: number;
  screenSelected: boolean;
  currentPlanet: Planet;
};

const Ship = ({
  props,
  setHoveredElement,
  setCurrentTutorialText,
  setTutorialIndex,
  setTutorialStep,
  setCurrentScreen,
  setScreenSelected,
  setPlanets,
  setEnteredAtmos,
  showDataCollected,
  talking,
  tutorial,
  tutorialStep,
  screenSelected,
  currentPlanet,
}: ShipProps) => {
  const { nodes, materials } = useGLTF(
    "/models/Cockpit.glb"
  ) as unknown as GLTFResult;

  // Configuration of sounds
  const [playShipSelect] = useSound(ShipSelect, { volume: 0.5 });
  const [playButtonClick] = useSound(ButtonClick, { volume: 0.5 });
  const [playLeverCrank] = useSound(LeverCrank, { volume: 0.5 });

  const handleClick = (name: string) => {
    if (talking || screenSelected) return;

    // Select the right sound to play
    if (name == "Ship Thrusters") {
      playLeverCrank();

      if (!tutorial) {
        setPlanets((prev) => ({
          ...prev,
          [currentPlanet.name]: {
            ...prev[currentPlanet.name],
            surfaceType: true,
          },
        }));

        showDataCollected();
      }

      // Enter atmosphere
      setEnteredAtmos(true);
    } else if (name === "Orbit Controls") {
      playButtonClick();

      // Update data for Color, Moons, Size, Rings
      if (!tutorial) {
        setPlanets((prev) => ({
          ...prev,
          [currentPlanet.name]: {
            ...prev[currentPlanet.name],
            color: true,
            moons: true,
            size: true,
            rings: true,
          },
        }));

        showDataCollected();
      }
    } else {
      playShipSelect();
      setCurrentScreen(name);
      setScreenSelected(true);
    }

    if (tutorial) {
      // Check for the current tutorial step
      checkTutorialStep(name);
    }
  };

  // Helper for checking the current tutorial step
  const checkTutorialStep = (name: string) => {
    if (TutorialManager[tutorialStep] == name) {
      setCurrentTutorialText([...TutorialDialogue[name]]);
      setTutorialIndex(-1);
      setTutorialStep((prev) => prev + 1);

      // Select the right sound to play
      if (name == "Ship Thrusters") {
        setPlanets((prev) => ({
          ...prev,
          [currentPlanet.name]: {
            ...prev[currentPlanet.name],
            surfaceType: true,
          },
        }));

        showDataCollected();
      } else if (name === "Orbit Controls") {
        // Update data for Color, Moons, Size, Rings
        setPlanets((prev) => ({
          ...prev,
          [currentPlanet.name]: {
            ...prev[currentPlanet.name],
            color: true,
            moons: true,
            size: true,
            rings: true,
          },
        }));

        showDataCollected();
      }
    }
  };

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cube003"
        geometry={nodes.Cube003.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube004"
        geometry={nodes.Cube004.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube005"
        geometry={nodes.Cube005.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube002"
        geometry={nodes.Cube002.geometry}
        material={materials["Screen Border"]}
        position={[2.844, 1.678, -0.513]}
        rotation={[-0.897, 0, 0]}
      />

      {/* Meshes that have screens */}
      <mesh
        name="Map"
        geometry={nodes.Screen001.geometry}
        position={[1.321, 1.769, -0.48]}
        rotation={[-0.901, 0, 0]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
        onPointerEnter={() => {
          if (!talking && !screenSelected) {
            document.body.style.cursor = "url('/images/Pointer.png'), auto";
            setHoveredElement("Map");
          }
        }}
        onPointerLeave={() => {
          document.body.style.cursor = "url('/images/Cursor.png'), auto";
          setHoveredElement(null);
        }}
        onClick={() => handleClick("Map")}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="Console"
        geometry={nodes.Plane.geometry}
        position={[-1.238, 1.769, -0.48]}
        rotation={[-0.901, 0, 0]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
        onPointerEnter={() => {
          if (!talking && !screenSelected) {
            document.body.style.cursor = "url('/images/Pointer.png'), auto";
            setHoveredElement("Console");
          }
        }}
        onPointerLeave={() => {
          document.body.style.cursor = "url('/images/Cursor.png'), auto";
          setHoveredElement(null);
        }}
        onClick={() => handleClick("Console")}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="Shields Console"
        geometry={nodes.Screen002.geometry}
        material={materials.Screen}
        position={[2.844, 1.678, -0.513]}
        rotation={[-0.897, 0, 0]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
        onPointerEnter={() => {
          if (!talking && !screenSelected) {
            document.body.style.cursor = "url('/images/Pointer.png'), auto";
            setHoveredElement("Shields Console");
          }
        }}
        onPointerLeave={() => {
          document.body.style.cursor = "url('/images/Cursor.png'), auto";
          setHoveredElement(null);
        }}
        onClick={() => handleClick("Shields Console")}
      >
        <LightMaterial />
      </mesh>

      <mesh
        name="MeterScreen"
        geometry={nodes.MeterScreen.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="MeterScreen001"
        geometry={nodes.MeterScreen001.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="BarScreen"
        geometry={nodes.BarScreen.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="BarScreen001"
        geometry={nodes.BarScreen001.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="BarScreen002"
        geometry={nodes.BarScreen002.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="ShipLights"
        geometry={nodes.ShipLights.geometry}
        position={[-3.453, 0.873, -0.785]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="ShipLights001"
        geometry={nodes.ShipLights001.geometry}
        position={[3.459, 0.873, -0.785]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="ShipLights002"
        geometry={nodes.ShipLights002.geometry}
        position={[-0.001, 0.701, -0.654]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="ShipLights003"
        geometry={nodes.ShipLights003.geometry}
        position={[-0.001, 5.28, -3.307]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.729, 1.623, 0.714]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>

      <mesh
        name="Cube001"
        geometry={nodes.Cube001.geometry}
        material={materials["Ship Metal"]}
      />
      <mesh
        name="Cube001_1"
        geometry={nodes.Cube001_1.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Ship Thrusters"
        geometry={nodes.Cube008.geometry}
        material={materials["Screen Border"]}
        onPointerEnter={() => {
          if (!talking && !screenSelected) {
            document.body.style.cursor = "url('/images/Pointer.png'), auto";
            setHoveredElement("Ship Thrusters");
          }
        }}
        onPointerLeave={() => {
          document.body.style.cursor = "url('/images/Cursor.png'), auto";
          setHoveredElement(null);
        }}
        onClick={() => handleClick("Ship Thrusters")}
      />
      <mesh
        name="Cube008_1"
        geometry={nodes.Cube008_1.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Cube008_2"
        geometry={nodes.Cube008_2.geometry}
        material={materials.Void}
      />
      <mesh
        name="Cube013"
        geometry={nodes.Cube013.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube013_1"
        geometry={nodes.Cube013_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Ship Orbit"
        geometry={nodes.Cube014.geometry}
        material={materials["Screen Border"]}
        onPointerEnter={() => {
          if (!talking && !screenSelected) {
            document.body.style.cursor = "url('/images/Pointer.png'), auto";
            setHoveredElement("Orbit Controls");
          }
        }}
        onPointerLeave={() => {
          document.body.style.cursor = "url('/images/Cursor.png'), auto";
          setHoveredElement(null);
        }}
        onClick={() => handleClick("Orbit Controls")}
      />
      <mesh
        name="Cube014_1"
        geometry={nodes.Cube014_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube020"
        geometry={nodes.Cube020.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube020_1"
        geometry={nodes.Cube020_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube021"
        geometry={nodes.Cube021.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube021_1"
        geometry={nodes.Cube021_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube003_1"
        geometry={nodes.Cube003_1.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube003_2"
        geometry={nodes.Cube003_2.geometry}
        material={materials.Void}
      />
      <mesh
        name="Cube003_3"
        geometry={nodes.Cube003_3.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Cylinder001_1"
        geometry={nodes.Cylinder001_1.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Cylinder001_2"
        geometry={nodes.Cylinder001_2.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cylinder002_1"
        geometry={nodes.Cylinder002_1.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Cylinder002_2"
        geometry={nodes.Cylinder002_2.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube016"
        geometry={nodes.Cube016.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube016_1"
        geometry={nodes.Cube016_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube022"
        geometry={nodes.Cube022.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube022_1"
        geometry={nodes.Cube022_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube023"
        geometry={nodes.Cube023.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube023_1"
        geometry={nodes.Cube023_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube024"
        geometry={nodes.Cube024.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube024_1"
        geometry={nodes.Cube024_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube025"
        geometry={nodes.Cube025.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube025_1"
        geometry={nodes.Cube025_1.geometry}
        material={materials.Button}
      />
    </group>
  );
};

useGLTF.preload("/models/Cockpit.glb");

export default Ship;
