/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

// Importing types
import { type GLTF } from "three-stdlib";
import { type JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube003_2: THREE.Mesh;
    Cube003_3: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
    Cylinder002_1: THREE.Mesh;
    Cylinder002_2: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube025_1: THREE.Mesh;
    Cube002: THREE.Mesh;
    Plane: THREE.Mesh;
    Screen001: THREE.Mesh;
    Screen002: THREE.Mesh;
    MeterScreen: THREE.Mesh;
    MeterScreen001: THREE.Mesh;
    BarScreen: THREE.Mesh;
    BarScreen001: THREE.Mesh;
    BarScreen002: THREE.Mesh;
    ShipLights: THREE.Mesh;
    ShipLights001: THREE.Mesh;
    ShipLights002: THREE.Mesh;
    ShipLights003: THREE.Mesh;
  };
  materials: {
    ["Ship Metal"]: THREE.MeshStandardMaterial;
    ["Ship Bearing"]: THREE.MeshStandardMaterial;
    ["Screen Border"]: THREE.MeshStandardMaterial;
    Void: THREE.MeshStandardMaterial;
    Button: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
  };
};

// Custom reusable components
const LightMaterial = () => {
  return (
    <meshStandardMaterial
      color={0x6fffe9}
      emissive={0x6fffe9}
      emissiveIntensity={4}
    />
  );
};

// Props for the Model
type ShipProps = {
  props?: JSX.IntrinsicElements["group"];
};

const Ship = ({ props }: ShipProps) => {
  const { nodes, materials } = useGLTF(
    "/models/Cockpit.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cube003"
        geometry={nodes.Cube003.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube004"
        geometry={nodes.Cube004.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube005"
        geometry={nodes.Cube005.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube002"
        geometry={nodes.Cube002.geometry}
        material={materials["Screen Border"]}
        position={[2.844, 1.678, -0.513]}
        rotation={[-0.897, 0, 0]}
      />

      {/* Meshes that have screens */}
      <mesh
        name="Screen001"
        geometry={nodes.Screen001.geometry}
        position={[1.321, 1.769, -0.48]}
        rotation={[-0.901, 0, 0]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
        onPointerEnter={() => {
          document.body.style.cursor = "url('/images/Pointer.png'), auto";
        }}
        onPointerLeave={() => {
          document.body.style.cursor = "url('/images/Cursor.png'), auto";
        }}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        position={[-1.238, 1.769, -0.48]}
        rotation={[-0.901, 0, 0]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="Screen002"
        geometry={nodes.Screen002.geometry}
        material={materials.Screen}
        position={[2.844, 1.678, -0.513]}
        rotation={[-0.897, 0, 0]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>

      <mesh
        name="MeterScreen"
        geometry={nodes.MeterScreen.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="MeterScreen001"
        geometry={nodes.MeterScreen001.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="BarScreen"
        geometry={nodes.BarScreen.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="BarScreen001"
        geometry={nodes.BarScreen001.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="BarScreen002"
        geometry={nodes.BarScreen002.geometry}
        material={materials.Screen}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="ShipLights"
        geometry={nodes.ShipLights.geometry}
        position={[-3.453, 0.873, -0.785]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="ShipLights001"
        geometry={nodes.ShipLights001.geometry}
        position={[3.459, 0.873, -0.785]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="ShipLights002"
        geometry={nodes.ShipLights002.geometry}
        position={[-0.001, 0.701, -0.654]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>
      <mesh
        name="ShipLights003"
        geometry={nodes.ShipLights003.geometry}
        position={[-0.001, 5.28, -3.307]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.729, 1.623, 0.714]}
        ref={(mesh) => mesh && mesh.layers.enable(1)}
      >
        <LightMaterial />
      </mesh>

      <mesh
        name="Cube001"
        geometry={nodes.Cube001.geometry}
        material={materials["Ship Metal"]}
      />
      <mesh
        name="Cube001_1"
        geometry={nodes.Cube001_1.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Cube008"
        geometry={nodes.Cube008.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube008_1"
        geometry={nodes.Cube008_1.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Cube008_2"
        geometry={nodes.Cube008_2.geometry}
        material={materials.Void}
      />
      <mesh
        name="Cube013"
        geometry={nodes.Cube013.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube013_1"
        geometry={nodes.Cube013_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube014"
        geometry={nodes.Cube014.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube014_1"
        geometry={nodes.Cube014_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube020"
        geometry={nodes.Cube020.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube020_1"
        geometry={nodes.Cube020_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube021"
        geometry={nodes.Cube021.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube021_1"
        geometry={nodes.Cube021_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube003_1"
        geometry={nodes.Cube003_1.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube003_2"
        geometry={nodes.Cube003_2.geometry}
        material={materials.Void}
      />
      <mesh
        name="Cube003_3"
        geometry={nodes.Cube003_3.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Cylinder001_1"
        geometry={nodes.Cylinder001_1.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Cylinder001_2"
        geometry={nodes.Cylinder001_2.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cylinder002_1"
        geometry={nodes.Cylinder002_1.geometry}
        material={materials["Ship Bearing"]}
      />
      <mesh
        name="Cylinder002_2"
        geometry={nodes.Cylinder002_2.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube016"
        geometry={nodes.Cube016.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube016_1"
        geometry={nodes.Cube016_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube022"
        geometry={nodes.Cube022.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube022_1"
        geometry={nodes.Cube022_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube023"
        geometry={nodes.Cube023.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube023_1"
        geometry={nodes.Cube023_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube024"
        geometry={nodes.Cube024.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube024_1"
        geometry={nodes.Cube024_1.geometry}
        material={materials.Button}
      />
      <mesh
        name="Cube025"
        geometry={nodes.Cube025.geometry}
        material={materials["Screen Border"]}
      />
      <mesh
        name="Cube025_1"
        geometry={nodes.Cube025_1.geometry}
        material={materials.Button}
      />
    </group>
  );
};

useGLTF.preload("/models/Cockpit.glb");

export default Ship;
